# Generated by Django 4.2.7 on 2024-03-02 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_api', '0002_alter_order_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
