# Generated by Django 4.2.7 on 2024-03-02 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0002_item_price_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(max_length=100, verbose_name='Номер сессии')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество товара')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
