# Generated by Django 4.2.7 on 2024-03-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_session',
            field=models.CharField(default=None, max_length=100, verbose_name='Номер сессии'),
        ),
    ]
