# Generated by Django 4.2.7 on 2024-03-03 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_price_id'),
        ('orders', '0002_alter_order_user_session'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Cart',
        ),
    ]
