# Generated by Django 4.2.7 on 2024-03-03 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_alter_cart_options_cart_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user_session',
        ),
    ]
