# Generated by Django 4.2.7 on 2024-03-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_cart_user_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Номер заказа'),
        ),
    ]
